### ISSUE TITLE
`searchTrip` and `stationBoard` throw errors: `'err': 'PARSE'`

### ISSUE THREAD

**Issue by phiyodr** [pajowu/db-python#4]
Awesome project! Thanks!

`api.searchLocation("Braunschweig Hbf")` is working perfectly, the response is  
```
response = self.cleanResponse(...)
> {'ver': '1.15', 'ext': 'DB.R19.04.a', 'lang': 'deu', 'id': 'hfw4ui6umku79w4s', 'cInfo': {'code': 'OK', 'url': '', 'msg': ''}, 'svcResL': [{'meth': 'LocMatch', 'err': 'OK', ...}
# 'err': 'OK'
```
Yet `api.searchTrip("Leipzig", "Berlin")` and `api.stationBoard("Braunschweig Hbf", duration=120)` throw errors. 

For both responses in [line 42](https://github.com/pajowu/db-python/blob/224bca2bc077c41737f6c6304560e65eedd245ce/bahn.py#L42) and [line 124](https://github.com/pajowu/db-python/blob/224bca2bc077c41737f6c6304560e65eedd245ce/bahn.py#L124) the results are  
```
response = self.cleanResponse(...)
> {'ver': '1.15', 'ext': 'DB.R19.04.a', 'lang': 'deu', 'id': '', 'err': 'PARSE', 'svcResL': []}
# 'err': 'PARSE'
```

Do you or anyone else know what needs to be changed to get the API working again. Many thanks in advance!

**Comment by pajowu** [comment]
Hey, thank's for opening this issue.

It's been some time since I wrote that code, so I assume that the internal API it uses changed. I currently don't have the resources to further investigate it, but would happily merge PRs if you want to.

A good source for how the API works (and possibly a library you could use instead) is the nodejs-library [db-hafas](https://github.com/public-transport/db-hafas).

**Comment by phiyodr** [comment]
I was afraid of both of these things ;) Thank you for the link! I will have a look.

**Comment by pajowu** [comment]
There is also a python library which was based on this code and is more maintained: https://github.com/FahrplanDatenGarten/pyhafas
